# Generated by Django 4.2.6 on 2025-07-31 04:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_item_mrp_item_origin_type_item_rate_item_tax'),
        ('TenderManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCheckListItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('tender_condition', models.TextField(blank=True, default='', null=True)),
                ('deviation_from_pia_norms', models.BooleanField(blank=True, default=False, null=True)),
                ('pia_remarks', models.TextField(blank=True, default='', null=True)),
                ('cost_implication', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost implication in INR', max_digits=18, null=True)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tender_checklist_items', to='TenderManagement.tender')),
                ('tender_checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tender_checklist_items', to='Masters.tenderchecklist')),
            ],
            options={
                'verbose_name': 'Tender CheckList Item',
                'verbose_name_plural': 'Tender CheckList Items',
                'unique_together': {('tender', 'tender_checklist')},
            },
        ),
    ]
