# Generated by Django 4.2.6 on 2025-08-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderManagement', '0002_tenderchecklistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderchecklistitems',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
