# Generated by Django 4.2.6 on 2025-08-19 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_initial'),
        ('Masters', '0009_currency_exchange_rate_item_currency'),
        ('TenderManagement', '0003_tenderchecklistitems_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Skipped')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Skipped')], default=1, null=True)),
                ('type', models.CharField(choices=[('BG', 'Bank Guarantee'), ('DD', 'Demand Draft'), ('NEFT', 'NEFT'), ('Cheque', 'Cheque')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_on', models.DateField()),
                ('due_expiry_date', models.DateField()),
                ('refunded_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Refunded', 'Refunded')], default='Pending', max_length=10)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'account_type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='ProjectManagement.project')),
            ],
            options={
                'verbose_name': 'Security Deposit',
                'verbose_name_plural': 'Security Deposits',
                'db_table': 'security_deposit',
            },
        ),
    ]
