# Generated by Django 4.2.6 on 2025-08-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenderManagement', '0004_securitydeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydeposit',
            name='extended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitydeposit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitydeposit',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='TenderManagement.tender'),
        ),
        migrations.AlterModelTable(
            name='securitydeposit',
            table=None,
        ),
    ]
