# Generated by Django 4.2.6 on 2025-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderManagement', '0005_securitydeposit_extended_on_securitydeposit_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydeposit',
            name='received_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitydeposit',
            name='type',
            field=models.CharField(choices=[('BG', 'Bank Guarantee'), ('SD', 'Security Deposit')], max_length=10),
        ),
    ]
