# Generated by Django 4.2.6 on 2025-08-20 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_initial'),
        ('Masters', '0009_currency_exchange_rate_item_currency'),
        ('TenderManagement', '0006_alter_securitydeposit_received_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Skipped')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Skipped')], default=1, null=True)),
                ('award_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contract_duration', models.IntegerField(blank=True, help_text='Duration in days', null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('validity_period', models.IntegerField(default=30, help_text='Validity period in days')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('performance_security_required', models.BooleanField(default=False)),
                ('performance_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('performance_security_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Issued'), (3, 'Accepted'), (4, 'Rejected'), (5, 'Expired')], default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('conditions_precedent', models.TextField(blank=True, null=True)),
                ('loa_document', models.FileField(blank=True, null=True, upload_to='letters_of_award/')),
                ('acceptance_document', models.FileField(blank=True, null=True, upload_to='letters_of_award/acceptance/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_award', to='Masters.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_award', to='ProjectManagement.project')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_award', to='TenderManagement.tender')),
            ],
            options={
                'verbose_name': 'Letter of Award',
                'verbose_name_plural': 'Letters of Award',
                'permissions': (('can_issue_loa', 'Can Issue Letter of Award'), ('can_approve_loa', 'Can Approve Letter of Award'), ('can_view_loa', 'Can View Letter of Award')),
            },
        ),
    ]
