# Generated by Django 4.2.6 on 2025-08-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_currency_exchange_rate_item_currency'),
        ('TenderManagement', '0007_letterofaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydeposit',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='Masters.account'),
        ),
    ]
