# Generated by Django 4.2.6 on 2025-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderManagement', '0009_letterofaward_bank_guarantee_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofaward',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='letterofaward',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='letterofaward',
            name='loa_number',
            field=models.CharField(blank=True, help_text='LOA Number', max_length=100, null=True),
        ),
    ]
