# Generated by Django 4.2.6 on 2025-08-26 13:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_tenderchecklist_pia_norms'),
        ('ProjectManagement', '0002_initial'),
        ('TenderManagement', '0010_remove_letterofaward_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Skipped')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Skipped')], default=1, null=True)),
                ('order_number', models.CharField(blank=True, help_text='Order Number', max_length=100, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contract_duration', models.IntegerField(blank=True, help_text='Duration in days', null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('performance_security_required', models.BooleanField(default=False)),
                ('performance_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('performance_security_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bank_guarantee_required', models.BooleanField(default=False)),
                ('bank_guarantee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Issued'), (3, 'Accepted'), (4, 'Rejected'), (5, 'Expired')], default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('conditions_precedent', models.TextField(blank=True, null=True)),
                ('order_document', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('acceptance_document', models.FileField(blank=True, null=True, upload_to='orders/acceptance/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Masters.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ProjectManagement.project')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='TenderManagement.tender')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'permissions': (('can_issue_order', 'Can Issue Order'), ('can_approve_order', 'Can Approve Order'), ('can_view_order', 'Can View Order')),
            },
        ),
    ]
