# Generated by Django 4.2.6 on 2025-07-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TenderManagement', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
        ('Masters', '0006_item_mrp_item_origin_type_item_rate_item_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plazo_tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='TenderManagement.plazotender'),
        ),
        migrations.AddField(
            model_name='project',
            name='sourceportal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='Masters.sourceportal'),
        ),
        migrations.AddField(
            model_name='project',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='Masters.tax'),
        ),
        migrations.AddField(
            model_name='project',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='TenderManagement.tender'),
        ),
        migrations.AddField(
            model_name='performancebankguaranteehistory',
            name='pbg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='performancebankguaranteehistory', to='ProjectManagement.performancebankguarantee'),
        ),
        migrations.AddField(
            model_name='performancebankguaranteehistory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='performancebankguaranteehistory', to='ProjectManagement.project'),
        ),
        migrations.AddField(
            model_name='performancebankguarantee',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='performancebankguarantee', to='ProjectManagement.project'),
        ),
    ]
