# Generated by Django 4.2.6 on 2025-07-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
        ('DynamicDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='Masters.companylogo'),
        ),
    ]
